FROM oven/bun:1.2.21 AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY tsconfig.json ./
COPY src ./src

RUN bun run compile:subscriber

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/dist/jobs-subscriber .

ENV NODE_ENV=production

CMD ["./jobs-subscriber"]
